Repository SuperFrog-Scheduler-2024/frontend, pull requests merged in 2024-05, with the labels that each got.

#14 Add FullCalendar plugin and update student table in SpiritDirectorView
  package-lock.json
  package.json
  src/views/SpiritDirectorView.vue
  src/views/SuperFrogView.vue
Labels: enhancement

#15 Fix fullCalendar by adding a new FullCalendar component
  package-lock.json
  package.json
  src/components/FullCalendar.vue
  src/views/SpiritDirectorView.vue
  src/views/SuperFrogView.vue
Labels: enhancement

#16 Fix calendar page
  package-lock.json
  src/components/FullCalendar.vue
  src/views/SpiritDirectorView.vue
  src/views/SuperFrogView.vue
Labels: bug

#20 Searching requests fix
  src/views/SpiritDirectorView.vue
  src/views/SuperFrogView.vue
Labels: bug, enhancement
